---
kind: pipeline
type: docker
name: default
globals:
  - &docker_creds
    username:
      from_secret: docker_hub_user
    password:
      from_secret: docker_hub_password
steps:
  - name: prepare
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache
  - name: build
    image: plugins/docker
    settings:
      repo: nightfuryest/drone-plugin-secret-to-wp-config
      tags:
        - latest
        - ${DRONE_COMMIT_BRANCH}
      create_repository: true
      use_cache: true
      <<: *docker_creds
    volumes:
      - name: docker
        path: /var/lib/docker
  - name: env
    image: nightfuryest/drone-plugin-secret-to-wp-config
    settings:
      template: wp-config.template
      file: wp-config.php
      envs:
        - DB_NAME
        - DB_USER
        - DB_PASSWORD
        - DB_HOST
      DB_NAME:
        from_secret: DB_NAME
      DB_USER:
        from_secret: DB_USER
      DB_PASSWORD:
        from_secret: DB_PASSWORD
      DB_HOST:
        from_secret: DB_HOST
  - name: test
    image: busybox
    commands:
      - ls -al
      - cat wp-config.php
volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/${DRONE_REPO}/docker

trigger:
  branch:
    - master
    - production
